### ISSUE TITLE
Tracks not matching and status code 400 when creating playlist

### ISSUE THREAD

**Issue by capsel22** [jjdenhertog/spotify-to-plex#7]
Hi,

I am trying to get the playlist sync to work, however I am a little struggling.

Plex connection shows green with message "We're connected to the selected Plex Media Server", so I think that's fine.
I am able to add users in "Connected Spotify users" and it can see my playlists, so I think that's also fine.
I can add manual Playlist under "Playlists & Albums"

However, I cannot get the "Plex Importer" to work.
When I open it, it shows 80 tracks not found, which is all of the tracks in this playlist.
I can see tracks on my plex server, however this seem to not be able to match it or find it.

Also, when I click "Create playlist" it shows below error.
![image](https://github.com/user-attachments/assets/81b27cd2-a645-41fb-a8b2-b8202a613a3d)

Here's an example of missing track
![image](https://github.com/user-attachments/assets/23f63c68-3055-4e8c-8ab7-8dc7997397f0)

and evidence it's in plex
![image](https://github.com/user-attachments/assets/6301e961-ac74-4e74-80fc-9007552c400f)

I dont really know what I am missing, or where to get any logs. Any help will be appreciated.

**Comment by jjdenhertog** [comment]
I see! I think a recent update broke the song matching. I will fix it tonight. It's probably a small thing.

**Comment by jjdenhertog** [comment]
@capsel22 I just ran some tests but all seems to be working. Your Spotify connection seems allright otherwise you wouldn't see any tracks.

The error 400 your getting is because your playlists has no tracks found. I will add a fix for that (making it unable to create a playlist if none of the tracks are found). But that won't solve your issue.

That leaves me up to guessing what the issue is on your end. But it must be something with the Plex Media Server connection. Can you maybe share some info:

- Have you tried both Plex Media Server urls, so also the local one (https://192.168.x.x)?
- Which Spotify Playlist are you using?
- Are you seeing any errors in the Plex console?

You can find the Plex console by clicking on the settings icon in Plex.
<img width="84" alt="image" src="https://github.com/user-attachments/assets/9d6ea893-a1b7-4376-933a-69325e85e271" />

And than the Console at the bottom right corner.
<img width="238" alt="image" src="https://github.com/user-attachments/assets/05ecc60b-3424-45ba-ad99-779320b96b16" />

When you keep that open, and then open the Plex Import you will see requests popping up in the console. Error requests are red, maybe you can share some data about what your seeying there. 

If you don't see any requests it might be that your Plex Media Server url is not right. Make sure that the ip address if the Plex Media Server matches the one using Spotify-to-Plex.

**Comment by capsel22** [comment]
@jjdenhertog 

hi, much appreciate your reply. Apologies I couldn't come back to you earlier
It makes sense for the 400 error, I suspected that was the case. So no issues there.

I think I know what's up. Following your advise on checking the console, after I click "Plex Importer" I get tonnes of these
![image](https://github.com/user-attachments/assets/e4698749-0ff2-421d-9af2-f87199ec0e26)

After I changed Secure Connections to Preferred from Required, this seem to have worked.
Would you know if there was a way to keep the Required setting for Secure Connections and the script still work?

**Comment by jjdenhertog** [comment]
@capsel22 thanks for diving in the console. Good to know the secure connection restrictions! I will enable this setting as well and do some debugging.

My first guess is that it's not possible. Because you run Spotify to Plex via an up address. And as a result you are always requesting from an insecure environment. But I'm not sure.

Does you Plex Media Server url at the main page start with https?

**Comment by capsel22** [comment]
> Does you Plex Media Server url at the main page start with https?

No. At the main page both the local LAN and WAN addresses start with http. I suspect if I could change this to https it may work with secure connection setting?

all my arr containers are using the https connection to plex and they dont have any issues speaking to Plex with the secure setting on.

**Comment by jjdenhertog** [comment]
@capsel22 correct, now you can try to do it manually. The config file plex.json, located in the persistent storage location contains a URI 

Could you try to change that to https and see if it works?

**Comment by capsel22** [comment]
> @capsel22 correct, now you can try to do it manually. The config file plex.json, located in the persistent storage location contains a URI
> 
> Could you try to change that to https and see if it works?

yes it works, I amended the url as per below and it seems to work.
![image](https://github.com/user-attachments/assets/ec7c2781-7332-4fdd-818d-ba716a8d5374)

![image](https://github.com/user-attachments/assets/3a90f664-1202-4f92-bf26-cb52cf6d175d)

**Comment by jjdenhertog** [comment]
Awesome, thanks for testing! I will add a checkbox in the intro screen so that anyone can toggle between secure/insecure.

**Comment by capsel22** [comment]
Thanks for all your help thus far.

I don't know if this is of any help but Sonarr and Radarr, after you authenticate with Plex, auto-generates these URLs, it must be able to get those URLs via API. Maybe something that could work for you too.
You can see it allows to pick secure or local (http) from the drop down
![image](https://github.com/user-attachments/assets/6fe608f3-8948-4566-b44b-d54dd1d3aa46)


Also, completely unrelated.
Would you consider adding your project to Unraid community Apps? I think this is an amazing project which deserves more recognition. If you are remotely interested there are some guidelines [here ](https://forums.unraid.net/topic/87144-ca-application-policies-notes/) There some bits and bobs you'd need from Unraid which I am super happy to assist with as I already kind of configured it for myself anyway.

**Comment by jjdenhertog** [comment]
@capsel22 I just pushed a new version, that marks the connections as 'https' when Plex has the flag for secure connections set to required.

About the Unraid: I haven't considered but it sounds great. I will create a item for it, just so I don't forget.

**Comment by capsel22** [comment]
Hi. yes I can see the https option now, and the sync works fine. Thank you.
